version: '3'
services:
  web:
    depends_on:
      - markup
      - exporter
    image: viewdoc/dev-nodejs
    volumes:
      - ./config:/usr/src/app/config
      - ./package.json:/usr/src/app/package.json
      - ./packages:/usr/src/app/packages
      - ./tmp:/usr/src/app/tmp
    command: npm run services:start_dev_web
    ports:
      - 4000:4000
  markup:
    image: viewdoc/markup
    volumes:
      - ./docker-services/markup:/usr/src/app
    ports:
      - 4100:4100
  exporter:
    image: viewdoc/dev-nodejs
    volumes:
      - ./config:/usr/src/app/config
      - ./package.json:/usr/src/app/package.json
      - ./packages:/usr/src/app/packages
      - ./tmp:/usr/src/app/tmp
    command: npm run services:start_dev_exporter
    ports:
      - 4200:4200
