const { writeFile } = require('fs-extra')
const path = require('path')
const { createTheme } = require('./lib')

const generateTheme = async () => {
  const header = `
    // This file is generated by generate-themes.js

    @import './base.scss';
  `
  await writeFile(path.join(__dirname, 'scss/tiny-light.scss'), `${header}${createTheme('light')}`)
  await writeFile(path.join(__dirname, 'scss/tiny-dark.scss'), `${header}${createTheme('dark')}`)
}

if (require.main === module) {
  generateTheme().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
